# Global settings applied to the whole site.
# “command” is your build command.
# “publish” is the directory to publish (relative to root of your repo).

[build]
  command = "npm run build"
  publish = "build"
  
[[redirects]]
  from = "/AlSupNet"
  to = "https://docs.google.com/forms/d/e/1FAIpQLScu-8wzYZAPhWeVQd9nzY03LV_gEm0XsDabctgHhb4biicbDw/viewform"
  status = 301
  force = false
  query = {path = ":path"}
  
[[redirects]]
  from = "/alumninetwork"
  to = "https://docs.google.com/forms/d/e/1FAIpQLScu-8wzYZAPhWeVQd9nzY03LV_gEm0XsDabctgHhb4biicbDw/viewform"
  status = 301
  force = false
  query = {path = ":path"}
  
[[redirects]]
  from = "/supportersnetwork"
  to = "https://docs.google.com/forms/d/e/1FAIpQLScu-8wzYZAPhWeVQd9nzY03LV_gEm0XsDabctgHhb4biicbDw/viewform"
  status = 301
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/2019conferenceguide"
  to = "https://drive.google.com/file/u/1/d/1XT_1xwSFzwa4lSAahUQ50zGeJRHn_GXM/view?usp=sharing"
  status = 301
  force = false
  query = {path = ":path"}
  
[[redirects]]
  from = "/betafrance"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSdcaWPkicipcyyhB5qhNrTmxxLymwTk7GmIti9sIuFZs9R1sA/viewform?usp=sf_link"
  status = 301
  force = false
  query = {path = ":path"}
